In [36]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from IPython.display import display, Markdown, Latex
from sklearn.datasets import make_blobs
from matplotlib.widgets import Slider

In [37]:
def my_softmax(z):
    ez = np.exp(z)
    sm = ez / np.sum(ez)
    return(sm)

In [38]:
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0, random_state=30)
print(f"X shape is: {X_train.shape}, Y shape is: {y_train.shape}")
print(f"X type is: {type(X_train)}, Y shape is: {type(y_train)}")
print(f"Top 10 (X):\n{X_train[:10]}\n")
print(f"Top 10 (Y):\n{y_train[:10]}\n")

X shape is: (2000, 2), Y shape is: (2000,)
X type is: <class 'numpy.ndarray'>, Y shape is: <class 'numpy.ndarray'>
Top 10 (X):
[[ 1.55508243  0.84801682]
 [-5.33749882  1.03397255]
 [-4.09353183  0.67843096]
 [-1.35928349 -1.49568732]
 [-0.67987836  3.15016353]
 [ 1.4685845   1.60076541]
 [-1.06017154 -2.23889878]
 [-6.05801535  2.46838122]
 [-1.59902629 -1.70935056]
 [ 4.27160051 -1.70297395]]

Top 10 (Y):
[2 0 0 1 2 2 1 0 1 3]



In [39]:
model = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4 , activation = 'softmax')])
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(), 
    optimizer = tf.keras.optimizers.Adam(0.01))
model.fit(
    X_train, y_train, epochs = 10)

Epoch 1/10
63/63 [==============================] - 0s 872us/step - loss: 0.3062
Epoch 2/10
63/63 [==============================] - 0s 864us/step - loss: 0.0402
Epoch 3/10
63/63 [==============================] - 0s 856us/step - loss: 0.0281
Epoch 4/10
63/63 [==============================] - 0s 856us/step - loss: 0.0244
Epoch 5/10
63/63 [==============================] - 0s 880us/step - loss: 0.0185
Epoch 6/10
63/63 [==============================] - 0s 872us/step - loss: 0.0165
Epoch 7/10
63/63 [==============================] - 0s 880us/step - loss: 0.0196
Epoch 8/10
63/63 [==============================] - 0s 888us/step - loss: 0.0261
Epoch 9/10
63/63 [==============================] - 0s 944us/step - loss: 0.0204
Epoch 10/10
63/63 [==============================] - 0s 892us/step - loss: 0.0143


In [40]:
p_nonpreferred = model.predict(X_train)
print(p_nonpreferred [:2])
print("largest value", np.max(p_nonpreferred), "smallest value", np.min(p_nonpreferred))

63/63 [==============================] - 0s 662us/step
[[5.9089739e-08 4.0276900e-05 9.9990886e-01 5.0726434e-05]
 [9.9998814e-01 1.1075232e-05 4.8876973e-07 2.6967777e-07]]
largest value 0.99999994 smallest value 9.6284636e-32
